#+TITLE: Canadian Federal Elections

=election= is a small [[https://www.rust-lang.org/][Rust]] program for processing [[https://elections.ca/content.aspx?section=ele&dir=pas&document=index&lang=e][vote data from Canadian Federal Elections]].

After building, see =election --help= for the available options.

* Table of Contents :TOC_2_gh:
- [[#getting-the-data][Getting the Data]]
- [[#interpretting-the-output][Interpretting the Output]]

* Getting the Data

Federal election data [[https://elections.ca/content.aspx?section=ele&dir=pas&document=index&lang=e][can be found here]]. =election= currently only supports 2019.
2021 will be supported as soon as the data is made public. To get the 2019 data,
navigate as follows:

+ 43rd General Election, October 21, 2019
+ Go to the raw data version (for researchers)
+ Canada / Provinces / Territories
+ Canada (Poll-by-poll Results - Format 2)

_You must use the Format 2 data._

Download this data and unzip its contents into =data/2019/= within your clone of
this repository.

* Interpretting the Output

All results are output as JSON. I use another tool, [[https://www.nushell.sh/][Nushell]], to format the
results into nice tables.

For example, to see how the [[https://www.partyrhino.ca/en/][Rhinoceros Party]] (a joke party) did in each riding:

#+begin_example
cargo run --release -- --party=rin | from json | reverse | first 10
#+end_example

#+begin_example
───┬────────────────────────────────────┬───────┬─────────────────────┬───────────────┬───────┬────────┬───────
 # │               riding               │ party │      last_name      │  first_name   │ votes │ ratio  │  won
───┼────────────────────────────────────┼───────┼─────────────────────┼───────────────┼───────┼────────┼───────
 0 │ Beauce                             │ Rhino │ Bernier             │ Maxime        │ 1084  │ 0.0182 │ false
 1 │ Gaspésie--Les Îles-de-la-Madeleine │ Rhino │ Cowboy              │ Jay           │  353  │ 0.0091 │ false
 2 │ Calgary Signal Hill                │ Rhino │ Bassett             │ Christina     │  511  │ 0.0080 │ false
 3 │ Papineau                           │ Rhino │ Cacereco Berthiaume │ Jean-Patrick  │  363  │ 0.0071 │ false
 4 │ Chicoutimi--Le Fjord               │ Rhino │ Bélanger            │ Line          │  299  │ 0.0068 │ false
 5 │ Québec                             │ Rhino │ CoRhino             │ Sébastien     │  349  │ 0.0064 │ false
 6 │ Hochelaga                          │ Rhino │ Blais-Leduc         │ Chinook       │  314  │ 0.0059 │ false
 7 │ Rosemont--La Petite-Patrie         │ Rhino │ Lavoie              │ Jos Guitare   │  346  │ 0.0057 │ false
 8 │ Mégantic--L'Érable                 │ Rhino │ Roy                 │ Damien        │  256  │ 0.0053 │ false
 9 │ LaSalle--Émard--Verdun             │ Rhino │ Bélanger            │ Rhino Jacques │  265  │ 0.0050 │ false
───┴────────────────────────────────────┴───────┴─────────────────────┴───────────────┴───────┴────────┴───────
#+end_example

Or perhaps we wish to see how every party did overall:

#+begin_example
cargo run --release -- --total | from json | sort-by votes | reverse
#+end_example

#+begin_example
────┬───────────────────────────────┬─────────┬────────
 #  │             party             │  votes  │ ratio
────┼───────────────────────────────┼─────────┼────────
  0 │ Conservative                  │ 6239227 │ 0.3433
  1 │ Liberal                       │ 6018728 │ 0.3312
  2 │ NDP-New Democratic Party      │ 2903722 │ 0.1598
  3 │ Bloc Québécois                │ 1387030 │ 0.0763
  4 │ Green Party                   │ 1189607 │ 0.0654
  5 │ People's Party                │ 294092  │ 0.0161
  6 │ Independent                   │  72546  │ 0.0039
  7 │ Christian Heritage Party      │  18901  │ 0.0010
  8 │ Rhino                         │  9538   │ 0.0005
  9 │ Libertarian                   │  8367   │ 0.0004
 10 │ VCP                           │  6300   │ 0.0003
 11 │ Animal Protection Party       │  4408   │ 0.0002
 12 │ ML                            │  4124   │ 0.0002
 13 │ Communist                     │  3905   │ 0.0002
 14 │ Pour l'Indépendance du Québec │  3815   │ 0.0002
 15 │ No Affiliation                │  1745   │ 0.0000
 16 │ PC Party                      │  1534   │ 0.0000
 17 │ Radical Marijuana             │   920   │ 0.0000
 18 │ CFF - Canada's Fourth Front   │   682   │ 0.0000
 19 │ UPC                           │   602   │ 0.0000
 20 │ National Citizens Alliance    │   510   │ 0.0000
 21 │ Stop Climate Change           │   296   │ 0.0000
 22 │ Nationalist                   │   281   │ 0.0000
────┴───────────────────────────────┴─────────┴────────
#+end_example
