#+TITLE: Canadian Federal Elections

=election= is a small [[https://www.rust-lang.org/][Rust]] program for processing [[https://elections.ca/content.aspx?section=ele&dir=pas&document=index&lang=e][vote data from Canadian Federal Elections]].

After building, see =election --help= for the available options.

* Table of Contents :TOC_2_gh:
- [[#getting-the-data][Getting the Data]]
- [[#interpretting-the-output][Interpretting the Output]]

* Getting the Data

Federal election data [[https://elections.ca/content.aspx?section=ele&dir=pas&document=index&lang=e][can be found here]]. =election= currently only supports 2019.
2021 will be supported as soon as the data is made public. To get the 2019 data,
navigate as follows:

+ 43rd General Election, October 21, 2019
+ Go to the raw data version (for researchers)
+ Canada / Provinces / Territories
+ Canada (Poll-by-poll Results - Format 2)

_You must use the Format 2 data._

Download this data and unzip its contents into =data/2019/= within your clone of
this repository.

* Interpretting the Output

All results are output as JSON. I use another tool, [[https://www.nushell.sh/][Nushell]], to format the
results into nice tables.

For example, to see how the [[https://www.partyrhino.ca/en/][Rhinoceros Party]] (a joke party) did overall:

#+begin_example
cargo run --release -- --party=rin | from json | reverse | first 10
#+end_example

#+begin_example
───┬────────────────────────────────────┬───────┬─────────────────────┬───────────────┬───────┬────────┬───────
 # │               riding               │ party │      last_name      │  first_name   │ votes │ ratio  │  won
───┼────────────────────────────────────┼───────┼─────────────────────┼───────────────┼───────┼────────┼───────
 0 │ Beauce                             │ Rhino │ Bernier             │ Maxime        │ 1084  │ 0.0182 │ false
 1 │ Gaspésie--Les Îles-de-la-Madeleine │ Rhino │ Cowboy              │ Jay           │  353  │ 0.0091 │ false
 2 │ Calgary Signal Hill                │ Rhino │ Bassett             │ Christina     │  511  │ 0.0080 │ false
 3 │ Papineau                           │ Rhino │ Cacereco Berthiaume │ Jean-Patrick  │  363  │ 0.0071 │ false
 4 │ Chicoutimi--Le Fjord               │ Rhino │ Bélanger            │ Line          │  299  │ 0.0068 │ false
 5 │ Québec                             │ Rhino │ CoRhino             │ Sébastien     │  349  │ 0.0064 │ false
 6 │ Hochelaga                          │ Rhino │ Blais-Leduc         │ Chinook       │  314  │ 0.0059 │ false
 7 │ Rosemont--La Petite-Patrie         │ Rhino │ Lavoie              │ Jos Guitare   │  346  │ 0.0057 │ false
 8 │ Mégantic--L'Érable                 │ Rhino │ Roy                 │ Damien        │  256  │ 0.0053 │ false
 9 │ LaSalle--Émard--Verdun             │ Rhino │ Bélanger            │ Rhino Jacques │  265  │ 0.0050 │ false
───┴────────────────────────────────────┴───────┴─────────────────────┴───────────────┴───────┴────────┴───────
#+end_example
